language: php

matrix:
  include:
    - php: 7.1
      env:
        - USE_FIXER="1"
    - php: 7.2
      env:
        - PHPUNIT_FLAGS="--coverage-clover ./tmp/clover.xml"
        - USE_FIXER="1"
    - php: 7.3
      env:
        - COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: nightly
      env:
        - COMPOSER_FLAGS="--ignore-platform-reqs"

install: composer install $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - '[[ $USE_FIXER = "1" ]] && vendor/bin/php-cs-fixer fix src/ --dry-run --verbose'

after_script:
  - '[[ $PHPUNIT_FLAGS = "" ]] || ./vendor/bin/php-coveralls --verbose'

branches:
  only:
    - master
